"""Superatom label → SMILES lookup table for abbreviation group expansion.

Provides a case-insensitive mapping from common abbreviation labels
(as they appear in ChemDraw CDXML ``NodeType="Fragment"`` nodes) to
SMILES strings.  Used by ``rdkit_utils.frag_to_mw()`` to compute
molecular weight of fragments that contain abbreviated groups, which
would otherwise return None (element-0 dummy atoms).

Data sources:

  1. ``superatom_data.json`` (project root) — ~2,850 entries generated
     from ChemScanner's superatom.txt (MIT/AGPL) plus additional common
     ChemDraw abbreviations.  Generated by
     ``experiments/build_superatom_json.py``.

  2. RDKit built-in abbreviations (BSD):
     ``rdkit.Chem.rdAbbreviations.GetDefaultAbbreviations()``
     ~40 entries used as secondary source (only adds entries not already
     in the JSON).

The SMILES represent standalone fragments whose first atom is the
attachment point.  When computing MW contribution to a parent molecule,
callers must subtract 1.008 Da per attachment bond (one implicit H is
lost when the fragment bonds to the parent).
"""

import json
import os
from typing import Dict, Optional

# Pre-cached MW values for superatom SMILES (avoids RDKit import at load time).
# Computed as: Descriptors.MolWt(Chem.MolFromSmiles(smiles)).
# This is the "standalone" MW — callers subtract 1.008 per attachment bond.
_MW_CACHE: Dict[str, float] = {}

# The lookup table: lowercase label → SMILES
_TABLE: Optional[Dict[str, str]] = None

# Path to the JSON data file (same directory as this module)
_JSON_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "superatom_data.json")


def _build_table() -> Dict[str, str]:
    """Build the case-insensitive label → SMILES lookup table."""
    table: Dict[str, str] = {}

    # Primary source: superatom_data.json
    if os.path.exists(_JSON_PATH):
        with open(_JSON_PATH, encoding="utf-8") as f:
            data = json.load(f)
        # JSON keys are already lowercase
        table.update(data)

    # Secondary source: RDKit built-in abbreviations
    try:
        from rdkit.Chem import rdAbbreviations
        for abbrev in rdAbbreviations.GetDefaultAbbreviations():
            label = abbrev.label.lower()
            if label and label not in table:
                sma = abbrev.smarts
                if sma:
                    table[label] = sma
            if hasattr(abbrev, "displayLabel"):
                dl = abbrev.displayLabel.lower()
                if dl and dl not in table:
                    table[dl] = abbrev.smarts
            if hasattr(abbrev, "displayLabelW"):
                dlw = abbrev.displayLabelW.lower()
                if dlw and dlw not in table:
                    table[dlw] = abbrev.smarts
    except (ImportError, AttributeError):
        pass  # RDKit not available; JSON entries suffice

    return table


def get_superatom_table() -> Dict[str, str]:
    """Return the label → SMILES lookup table (singleton, built on first call).

    Keys are lowercase.  Values are SMILES strings representing the
    standalone fragment (first atom = attachment point).
    """
    global _TABLE
    if _TABLE is None:
        _TABLE = _build_table()
    return _TABLE


def lookup_smiles(label: str) -> Optional[str]:
    """Look up a superatom label and return its SMILES, or None."""
    return get_superatom_table().get(label.lower())


def lookup_mw(label: str) -> Optional[float]:
    """Look up a superatom label and return its standalone MW, or None.

    The returned MW is for the standalone fragment (includes all implicit H).
    Callers computing MW for an attached group should subtract 1.008 per
    attachment bond (one H is lost when the group bonds to the parent).

    Requires RDKit — returns None if RDKit is not available.
    """
    smiles = lookup_smiles(label)
    if smiles is None:
        return None

    # Check cache
    if smiles in _MW_CACHE:
        return _MW_CACHE[smiles]

    try:
        from rdkit import Chem
        from rdkit.Chem import Descriptors
        # Try parsing as SMILES first (most entries), then as SMARTS
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            mol = Chem.MolFromSmarts(smiles)
            if mol is not None:
                mol = Chem.AddHs(mol)
        if mol is None:
            return None
        mw = Descriptors.MolWt(mol)
        _MW_CACHE[smiles] = mw
        return mw
    except (ImportError, Exception):
        return None


def get_abbrev_label(node) -> Optional[str]:
    """Extract the visible abbreviation label text from a CDXML node.

    Expects an ``<n NodeType="Fragment">`` element.  The label is in
    a ``<t><s>...</s></t>`` child of the ``<n>`` (not inside the inner
    ``<fragment>``).

    Returns the concatenated text of all ``<s>`` elements, or None.
    """
    for t in node.findall("t"):
        parts = []
        for s in t.findall("s"):
            if s.text:
                parts.append(s.text)
        if parts:
            return "".join(parts)
    return None
